### ISSUE TITLE
Slider'ın assetini değiştirirken hot reload çalışmıyor ve uygulamayı yeniden başlatmak gerekiyor

### ISSUE THREAD

**Issue by tolgasozbir** [mysCod3r/custom_slider#1]
Şöyle bir sorunla karşılaştım: Slider'ın assetini değiştirmek istediğimde, örneğin star'dan heart'a geçiş yapmak istediğimde hot reload çalışmıyor. Bunun yerine uygulamayı yeniden başlatmam gerekiyor. Sorunu şu şekilde çözdüm:

<hr>

https://github.com/mysCod3r/custom_slider/blob/0035a81a5516cf05be335d41a54fdd4c9d1bf678/lib/src/slider.dart#L36-L46

Sorun: _path ve _borderPath değişkenleri final olarak işaretlenmiş ve sadece initState anında değerleri alınıyor

<hr>

Çözüm1: final keywordünü kaldırdım ve initState içerisindeki atama işlemini bir fonksiyona taşıdım. Bu fonksiyonu hem initState hem de didUpdateWidget fonksiyonlarında çağırdım. Böylece ilk atamadan sonra farklı svg path'i verilirse didUpdateWidget tetiklenerek _path ve _borderPath değişkenlerine yeni değerler atanmış olacak ve sorun çözülmüş olacak.

Çözüm2: Widget'in constructor'undan direkt olarak değerleri okuyarak, _path ve _borderPath değişkenlerine ve initState'e ihtiyaç duymadan sorunu çözebiliriz. Widget içerisindeki "nameToPath(String name)" fonksiyonunu kullanarak, widget'tan gelen değerleri bu fonksiyona verip, gerekli yerlerde çağırdığımızda sorun çözmüş olduk. Ayrıca bu çözüm  yaklaşık 10 satır koddan kurtardı bizi

https://github.com/mysCod3r/custom_slider/blob/0035a81a5516cf05be335d41a54fdd4c9d1bf678/lib/src/slider.dart#L64-L69
https://github.com/mysCod3r/custom_slider/blob/0035a81a5516cf05be335d41a54fdd4c9d1bf678/lib/src/slider.dart#L134-L139

66 ve 137. satırları şöyle değiştirebiliriz
```Dart
nameToPath(widget.borderNameOrPath!), //66. satır
```

```Dart
nameToPath(widget.nameOrPath), //137. satır
```

**Comment by mysCod3r** [comment]
2. yöntem daha az kodla yazılabilmesine rağmen widget her yeniden çizilmesinde nameToPath fonksiyonunu çalıştıracağı için gereksiz performans kaybına sebep olacaktı o yzden 1. yöntemle çözüp güncelledim. Katkın için teşekkürler.
